(() => {
  const cfg = window.SHUGAA_CONFIG;
  const client = supabase.createClient(cfg.supabaseUrl, cfg.supabasePublishableKey);
  const state = {session:null,role:"viewer",people:[],relations:[],marriages:[],branches:[],cy:null};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const authScreen=$("#authScreen"), app=$("#app"), authMsg=$("#authMsg"), adminMsg=$("#adminMsg");

  function toast(msg,ms=2600){const el=$("#toast");el.textContent=msg;el.classList.remove("hidden");clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add("hidden"),ms)}
  function confidenceLabel(v){return ({documented:"موثق",family_tradition:"متوارث عائليًا",likely:"مرجح",uncertain:"غير مؤكد"})[v]||"غير محدد"}
  function genderIcon(g){return g==="female"?"ن":g==="male"?"ش":"•"}
  function yearText(p){const b=p.birth_year||(p.birth_date?String(p.birth_date).slice(0,4):"");const d=p.death_year||(p.death_date?String(p.death_date).slice(0,4):"");if(b||d)return `${b||"؟"} — ${p.is_living?"حتى الآن":(d||"؟")}`;return p.is_living?"على قيد الحياة":"التاريخ غير مسجل"}
  function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[s])}
  function toNullInt(v){const n=parseInt(v,10);return Number.isFinite(n)?n:null}

  async function getRole(){const uid=state.session?.user?.id;if(!uid)return"viewer";const{data,error}=await client.from("profiles").select("role").eq("id",uid).maybeSingle();if(error)console.warn(error);return data?.role||"viewer"}
  async function loadData(){const [a,b,c,d]=await Promise.all([client.from("people").select("*").order("full_name_ar"),client.from("parent_child_relations").select("*"),client.from("marriages").select("*"),client.from("branches").select("*")]);for(const r of[a,b,c,d])if(r.error)throw r.error;state.people=a.data||[];state.relations=b.data||[];state.marriages=c.data||[];state.branches=d.data||[];renderStats();renderPeople();fillParentSelects();renderTree()}
  function renderStats(){$("#statPeople").textContent=state.people.length;$("#statRelations").textContent=state.relations.length;$("#statMarriages").textContent=state.marriages.length;$("#statBranches").textContent=state.branches.length}
  function renderPeople(filter=""){const grid=$("#peopleGrid"),empty=$("#peopleEmpty"),q=filter.trim().toLowerCase();const rows=state.people.filter(p=>!q||p.full_name_ar.toLowerCase().includes(q)||(p.full_name_en||"").toLowerCase().includes(q));grid.innerHTML="";empty.classList.toggle("hidden",rows.length>0);rows.forEach(p=>{const card=document.createElement("article");card.className="person-card";card.innerHTML=`<div class="avatar">${genderIcon(p.gender)}</div><div><h3>${escapeHtml(p.full_name_ar)}</h3><p>${escapeHtml(yearText(p))}</p><p>${escapeHtml(confidenceLabel(p.record_confidence))}</p></div>`;card.addEventListener("click",()=>openPerson(p.id));grid.appendChild(card)})}
  function fillParentSelects(){const father=$("#pFather"),mother=$("#pMother");father.innerHTML='<option value="">— غير معروف / لا يوجد —</option>';mother.innerHTML='<option value="">— غير معروفة / لا يوجد —</option>';state.people.forEach(p=>{if(p.gender!=="female")father.add(new Option(p.full_name_ar,p.id));if(p.gender!=="male")mother.add(new Option(p.full_name_ar,p.id))})}
  function buildTreeElements(){const e=[];state.people.forEach(p=>e.push({data:{id:p.id,label:p.full_name_ar,gender:p.gender}}));state.relations.forEach(r=>e.push({data:{id:`pc-${r.id}`,source:r.parent_id,target:r.child_id,kind:"parent"}}));state.marriages.forEach(m=>e.push({data:{id:`m-${m.id}`,source:m.person1_id,target:m.person2_id,kind:"marriage"}}));return e}
  function renderTree(){const c=$("#cy"),empty=$("#treeEmpty");if(!state.people.length){c.classList.add("hidden");empty.classList.remove("hidden");return}c.classList.remove("hidden");empty.classList.add("hidden");if(state.cy)state.cy.destroy();state.cy=cytoscape({container:c,elements:buildTreeElements(),wheelSensitivity:.18,minZoom:.25,maxZoom:2.4,style:[{selector:"node",style:{"background-color":"#fffaf0","border-width":2,"border-color":"#b8892d","label":"data(label)","text-wrap":"wrap","text-max-width":130,"font-family":"Arial","font-size":12,"font-weight":700,"color":"#173f35","width":150,"height":58,"shape":"round-rectangle","text-valign":"center","text-halign":"center","overlay-opacity":0}},{selector:'node[gender = "female"]',style:{"border-color":"#c69aa3","background-color":"#fff8f8"}},{selector:'edge[kind = "parent"]',style:{"width":2,"line-color":"#245f51","target-arrow-color":"#245f51","target-arrow-shape":"triangle","curve-style":"bezier","arrow-scale":.75}},{selector:'edge[kind = "marriage"]',style:{"width":2,"line-style":"dashed","line-color":"#b8892d","curve-style":"bezier"}},{selector:".search-hit",style:{"background-color":"#f4dda4","border-width":4,"border-color":"#0f4d3f"}}],layout:{name:"dagre",rankDir:"TB",rankSep:100,nodeSep:45,edgeSep:18,padding:35}});state.cy.on("tap","node",ev=>openPerson(ev.target.id()))}
  function getPerson(id){return state.people.find(p=>p.id===id)}
  function familyOf(id){const fr=state.relations.find(r=>r.child_id===id&&r.parent_role==="father"),mr=state.relations.find(r=>r.child_id===id&&r.parent_role==="mother"),kids=state.relations.filter(r=>r.parent_id===id).map(r=>r.child_id),sp=state.marriages.flatMap(m=>m.person1_id===id?[m.person2_id]:m.person2_id===id?[m.person1_id]:[]);return{father:fr?getPerson(fr.parent_id):null,mother:mr?getPerson(mr.parent_id):null,children:[...new Set(kids)].map(getPerson).filter(Boolean),spouses:[...new Set(sp)].map(getPerson).filter(Boolean)}}
  function openPerson(id){const p=getPerson(id);if(!p)return;const f=familyOf(id);$("#profileName").textContent=p.full_name_ar;$("#profileLife").textContent=yearText(p);$("#profileConfidence").textContent=confidenceLabel(p.record_confidence);$("#profileAvatar").textContent=genderIcon(p.gender);$("#profileFather").textContent=f.father?.full_name_ar||"—";$("#profileMother").textContent=f.mother?.full_name_ar||"—";$("#profileSpouses").textContent=f.spouses.length?f.spouses.map(x=>x.full_name_ar).join("، "):"—";$("#profileChildren").textContent=f.children.length?f.children.map(x=>x.full_name_ar).join("، "):"—";$("#profileBio").textContent=p.bio||"لا توجد نبذة مسجلة.";$("#personModal").classList.remove("hidden")}
  function closeModal(){$("#personModal").classList.add("hidden")}
  function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-btn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==="tree"&&state.cy)setTimeout(()=>state.cy.resize(),30);window.scrollTo({top:0,behavior:"smooth"})}
  function applyRoleUI(){const can=["admin","editor"].includes(state.role);$$('.admin-only').forEach(el=>el.classList.toggle('hidden',!can));$("#userRoleBadge").textContent=state.role==="admin"?"مدير":state.role==="editor"?"محرر":"مشاهد"}
  async function enterApp(session){state.session=session;state.role=await getRole();applyRoleUI();authScreen.classList.add("hidden");app.classList.remove("hidden");try{await loadData()}catch(err){console.error(err);toast("تعذر تحميل بيانات الشجرة. تحقق من الصلاحيات والاتصال.")}}
  async function signOut(){await client.auth.signOut();state.session=null;state.people=[];state.relations=[];state.marriages=[];state.branches=[];app.classList.add("hidden");authScreen.classList.remove("hidden")}

  $("#loginForm").addEventListener("submit",async e=>{e.preventDefault();authMsg.textContent="جاري الدخول...";const email=$("#email").value.trim(),password=$("#password").value;const{data,error}=await client.auth.signInWithPassword({email,password});if(error){authMsg.textContent="تعذر تسجيل الدخول: "+error.message;return}authMsg.textContent="";await enterApp(data.session)});
  $("#forgotBtn").addEventListener("click",async()=>{const email=$("#email").value.trim();if(!email){authMsg.textContent="اكتب بريدك أولًا.";return}const{error}=await client.auth.resetPasswordForEmail(email,{redirectTo:window.location.href});authMsg.textContent=error?("تعذر إرسال الرابط: "+error.message):"تم إرسال رابط استعادة كلمة المرور إذا كان البريد مسجلًا."});
  $("#logoutBtn").addEventListener("click",signOut);$$('.nav-btn[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));$$('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModal));
  $("#peopleSearch").addEventListener("input",e=>renderPeople(e.target.value));$("#treeSearch").addEventListener("input",e=>{if(!state.cy)return;const q=e.target.value.trim().toLowerCase();state.cy.nodes().removeClass("search-hit");if(!q)return;const hits=state.cy.nodes().filter(n=>(n.data("label")||"").toLowerCase().includes(q));hits.addClass("search-hit");if(hits.length)state.cy.animate({fit:{eles:hits,padding:120},duration:350})});
  $("#fitTreeBtn").addEventListener("click",()=>state.cy?.fit(undefined,40));$("#relayoutBtn").addEventListener("click",()=>state.cy?.layout({name:"dagre",rankDir:"TB",rankSep:100,nodeSep:45,padding:35}).run());
  $("#addPersonForm").addEventListener("submit",async e=>{e.preventDefault();if(!["admin","editor"].includes(state.role))return;adminMsg.textContent="جاري الحفظ...";const person={full_name_ar:$("#pName").value.trim(),gender:$("#pGender").value,birth_year:toNullInt($("#pBirthYear").value),death_year:toNullInt($("#pDeathYear").value),is_living:$("#pLiving").checked,record_confidence:$("#pConfidence").value,bio:$("#pBio").value.trim()||null,created_by:state.session.user.id,updated_by:state.session.user.id};const{data,error}=await client.from("people").insert(person).select().single();if(error){adminMsg.textContent="خطأ: "+error.message;return}const rels=[];if($("#pFather").value)rels.push({parent_id:$("#pFather").value,child_id:data.id,parent_role:"father",relation_kind:"biological",confidence:$("#pConfidence").value,created_by:state.session.user.id});if($("#pMother").value)rels.push({parent_id:$("#pMother").value,child_id:data.id,parent_role:"mother",relation_kind:"biological",confidence:$("#pConfidence").value,created_by:state.session.user.id});if(rels.length){const{error:re}=await client.from("parent_child_relations").insert(rels);if(re){adminMsg.textContent="تمت إضافة الشخص لكن حدث خطأ في ربط الوالدين: "+re.message;await loadData();return}}e.target.reset();$("#pLiving").checked=true;adminMsg.textContent="تمت إضافة الشخص بنجاح ✅";await loadData();toast("تمت إضافة الشخص إلى شجرة آل شجاع")});
  client.auth.getSession().then(async({data})=>{if(data.session)await enterApp(data.session)});client.auth.onAuthStateChange(async(_e,session)=>{if(!session&&state.session)await signOut()});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));
})();